# Generated by Django 5.2.10 on 2026-01-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='user',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество оценок'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Группы, в которых состоит пользователь.', related_name='custom_user_set', to='auth.group', verbose_name='группы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Верифицирован'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Средний рейтинг'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_ids/', verbose_name='Фото студенческого билета'),
        ),
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, max_length=255, verbose_name='Университет'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Конкретные разрешения пользователя.', related_name='custom_user_permissions_set', to='auth.permission', verbose_name='разрешения пользователя'),
        ),
    ]
